project:
  type: website
  output-dir: docs
  render:
    - index.qmd

website:
  title: "Wolfgang Huber's tweets 2015-24"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cerulean
    toc: false
    embed-resources: false
    page-layout: full
    css: tweetarchive.css
