project:
  type: website
  output-dir: docs
  render:
    - index.qmd

website:
  title: "@nekton4plankton tweets 2012-2024"
  navbar:
    search: true
    left:
      - href: https://bsky.app/profile/nekton4plankton.bsky.social
        text: now on bluesky
      - href: https://alexanderlabwhoi.github.io/
        text: lab website

format:
  html:
    theme: solar
    toc: false
    embed-resources: false
    page-layout: full
    css: tweetarchive.css
